apiVersion: v2
name: external-secrets-operator
version: 1.0.0
description: A Helm chart for deploying external-secrets-operator
appVersion: 1.0.0
dependencies:
  - name: external-secrets
    version: 0.10.2
    repository: oci://ghcr.io/external-secrets/charts
